import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { ISSHProvider } from './interfaces/ssh-provider.interface';
import { SSHKeyDto } from '../dto/ssh-key.dto';
import { CloudProvider } from '../../providers/enums/cloud-provider.enum';
import {
  Configuration,
  SSHKeysApi,
} from 'src/modules/providers/implementations/hetzner/generated';

@Injectable()
export class HetznerSSHProviderService implements ISSHProvider {
  private readonly logger = new Logger(HetznerSSHProviderService.name);
  private readonly basePath: string;

  constructor(private readonly configService: ConfigService) {
    this.basePath = this.configService.get<string>(
      'HETZNER_API_BASE_PATH',
      'https://api.hetzner.cloud/v1',
    );
  }

  async listSSHKeys(): Promise<SSHKeyDto[]> {
    try {
      // Get API token directly from environment or config
      // This avoids circular dependency with AccessService
      const apiToken = this.configService.get<string>('HETZNER_API_TOKEN');

      if (!apiToken) {
        this.logger.warn('No Hetzner API token configured');
        return [];
      }

      const configuration = new Configuration({
        accessToken: apiToken,
        basePath: this.basePath,
      });

      const sshKeysApi = new SSHKeysApi(configuration);
      const response = await sshKeysApi.listSshKeys();

      return response.data.ssh_keys
        .filter((sshKey) => this.isFluiManaged(sshKey.labels))
        .map((sshKey) => this.mapHetznerSSHKeyToDto(sshKey));
    } catch (error) {
      this.logger.error('Failed to list SSH keys from Hetzner API', error);
      return [];
    }
  }

  async testConnection(): Promise<{ success: boolean; error?: string }> {
    try {
      await this.listSSHKeys();
      return { success: true };
    } catch (error) {
      return { success: false, error: error.message };
    }
  }

  private mapHetznerSSHKeyToDto(sshKey: any): SSHKeyDto {
    return {
      id: sshKey.id.toString(),
      name: sshKey.name,
      publicKey: sshKey.public_key,
      fingerprint: sshKey.fingerprint,
      type: this.extractKeyType(sshKey.public_key),
      createdAt: new Date(sshKey.created),
      updatedAt: new Date(sshKey.created),
      source: CloudProvider.HETZNER,
      syncedFromProvider: true,
      providerKeyId: sshKey.id.toString(),
      isActive: sshKey.is_active,
      autoGenerated: false,
    };
  }

  private isFluiManaged(
    labels: Record<string, string> | null | undefined,
  ): boolean {
    if (!labels) return false;
    return (
      labels['managed-by'] === 'flui-cloud' &&
      labels['flui-resource-type'] === 'ssh-key'
    );
  }

  private extractKeyType(publicKey: string): string {
    if (publicKey.startsWith('ssh-rsa')) return 'rsa';
    if (publicKey.startsWith('ssh-ed25519')) return 'ed25519';
    if (publicKey.startsWith('ssh-dss')) return 'dsa';
    if (publicKey.startsWith('ecdsa-sha2')) return 'ecdsa';
    return 'unknown';
  }
}
