export enum AppBuildStatus {
  PENDING = 'PENDING',
  CLONING = 'CLONING',
  ANALYZING = 'ANALYZING',
  BUILDING = 'BUILDING',
  PUSHING = 'PUSHING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}
