import { SSHKey } from '../interfaces/ssh-key.interface';
import { SSHKeyDto } from '../dto/ssh-key.dto';

export class SSHKeyMapper {
  static toDto(sshKey: SSHKey): SSHKeyDto {
    return {
      id: sshKey.id,
      name: sshKey.name,
      publicKey: sshKey.publicKey,
      fingerprint: sshKey.fingerprint,
      type: sshKey.type,
      isActive: sshKey.isActive,
      autoGenerated: sshKey.autoGenerated,
      lastUsed: sshKey.lastUsed,
      createdAt: sshKey.createdAt,
      updatedAt: sshKey.updatedAt,
      tags: sshKey.tags || {},
      providerKeyMappings: sshKey.providerKeyMappings || {},
    };
  }

  static toDtoList(sshKeys: SSHKey[]): SSHKeyDto[] {
    return sshKeys.map((sshKey) => this.toDto(sshKey));
  }
}
